import ThemeProvider from '../utility/ThemeProvider'
import './globals.css'
import Navbar from './NavBar'
import { Toaster } from "react-hot-toast"

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by yours truly',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
